server:
  port: 8090

services:
  products:
    url: http://localhost:8888
    path: /products

http:
  client:
    timeout:
      read: 10
      call: 10
    retry:
      max-retries: 3
      retry-delay: 5
      max-retry-delay: 30